* org_arc_todo

Eventually, =org_arc_todo= would help you to sync your local notes in
Org-mode with the project tasks in Phabricator, but it is not quite
there yet. At this moment, it can only send your notes to Phabricator.
* Installation 
  
  =org-arc_todo= depends on the =Arcanist= tool. The minimal
  configuration for =Arcanist= is the URI to the Phabricator server
  and credential tokens.

  I would recommend to set these two variables at least at user level
  so that you could use =org_arc_todo= anywhere regardless the working
  directory (/default-directory/ in Emacs).
* Usage
** Send Org-mode Notes to Phabricator

 =org_arc_todo= will

 1. file your notes to the relevant projects in Phabricator, and
 2. add subscribers to the created tasks.

 Here is an example: 

 #+begin_example
 \* Tasks
   :PROPERTIES:
   :arc_project: org_arc_todo project
   :END:
 \*\* Fix documentation
    :PROPERTIES:
    :arc_user: myself, dory, deep
    :END:
 #+end_example

 If you place your point under Fix documentation node, and invoke the
 *arcanist-todo* command, it will parse the node and dump the output
 in the /\*arcanist-todo\*/ buffer,

 #+begin_example

 ## [summary of task]
 "Fix documentation"
 ## [project]
 --project="org_arc_todo project"
 ## [subscribers]
 --cc="myself"
 ## [subscribers]
 --cc="dory"
 ## [subscribers]
 --cc="deep"
 #+end_example

 You could add some thing manually and or just leave it as it is, and
 then invoke the *arcanist-todo-finish* command, it will parse the
 buffer content and send it to phabricator. You will see message in
 the echo area like this

 #+begin_example
 Created task T1353: 'Fix documentation' at http://195.2.1.40:80/T47
 #+end_example

** NEXT Fetch Tasks Phabricator 

** NEXT Sync Between Org-mode and Phabricator 
    

* Future Development and Collaboration 
  At this stage, =org_arc_todo= uses the =arc todo= to send notes to
  Phabricator, and we cannot do much with the the =arc todo= command.
  If there's new feature introduced to =arc todo=, I will update
  =org_arc_todo= accordingly.

  To sync between Org-mode and Phabricator, we have to utilise the
  Phabricator's API, but I can't find useful documentation about it.
  If you know how, please share it with me and I will update this project.
